### ISSUE TITLE
Kenya testing data

### ISSUE THREAD

**Issue by gundersen** [developmentseed/kenya-bank#7]
@mayarichman how did the new data we got from the Bank today look? What can we do with the data? Any questions / follow up needed?

**Comment by mayarichman** [comment]
@gundersen The test results seems to be very dismal compared to [the map](http://dl.dropbox.com/u/24683141/exam_percentage_county.gif) we saw in the email. We are trying to find some meta-data on what they consider passing and failing grades, but the way we calculated it, all counties have far more students failing. 

The data is also broken down by student, and then by school and onward, but we have no lat/longs for these schools in 2010, so I aggregated the number to the county level.

Could you ask them for any meta-data they might have on the two datasets they have given us or on the maps from the KCPE 2010 Results Map from the email?

I am weary to misrepresent the dataset with our own scale if they are expecting the positive test results on the map.

**Comment by gundersen** [comment]
@mayarichman First, if we did know the grades and all the meta data was ok would this data still be helpful? We can just do a county map on it right? Why can't we join to the school data that we have already mapped?

**Comment by davejohn** [comment]
@gundersen, cc @mayarichman 

We can to a movetip of average exam results by county (nice big letter grade maybe) on top of poverty choropleth, or GDP per capita spent by county. We can't join to school data because names will likely be different (two data sets from different time periods), and it's a better story to show grade averages by county on poverty/GDP spending info. 

Like Maya said, we need metadata on the exam results to do further processing, and we need the GDP per capita spending. I think they also expect this as it is in their education report forwarded to us from Edward. 

### Next actions
- I'm waiting on emailing Tracey (their Kenya data person) because not sure if they know we're working on this yet. Thoughts?

**Comment by gundersen** [comment]
@davejohn y, draft a note to tracy(?) or Catherine? make sure Edward is CCed on this. 

hey @mayarichman get a devseed email address. Ask Bonnie.

**Comment by davejohn** [comment]
@gundersen, good to send [this note](https://gist.github.com/f32de05515a7dc9fac4b) to Tracey with Edward Cc'd?

cc @mayarichman

**Comment by gundersen** [comment]
@davejohn y, send that note. Keep me on CC for now.

**Comment by davejohn** [comment]
done with Kenya data questions, this is all captured in methodology on site.
